### ISSUE TITLE
Layer shell surfaces still modify the exclusion area when the session is locked

### ISSUE THREAD

**Issue by mattkae** [MirServer/mir#3202] opened 2024-01-23 15:43 UTC
## Repro
- Run an application that uses the layer shell protocol (like `waybar`)
- Next, run an application that relies on `ext_session_lock_manager_v1`
- It is expected that the lockscreen surface can take up the full screen
- However, note that it is excluded from the region where `waybar` formally was being rendered

**Comment by AlanGriffiths** [comment] 2024-01-23 15:51
Duplicate of #1992 (see also #3125)

**Closed by AlanGriffiths** 2024-01-23 15:51 UTC
Labels: bug
