### ISSUE TITLE
[XWayland] CLion popup window is transparent to input

### ISSUE THREAD

**Issue by RAOF** [MirServer/mir#2326] opened 2022-02-17 07:12 UTC
The little bottom-right popup window that CLion uses to notify of background things - plugin updates and so on - is transparent to input on egmde. You can't click on any of the hyperlinks, and clicks in that area go to the content window behind.

It's not clear to me what's happening here, as I can't find that window the X11 window tree *at all*.

**Comment by AlanGriffiths** [comment] 2022-02-17 11:40
Testing with egmde-155-mir2.7.0~rc2-snap188 I can't reproduce.

I've not yet seen the popup come up as a notification. If I click on the icon to show the popup there's no problem. Maybe that's a significant difference?

**Comment by AlanGriffiths** [comment] 2022-02-21 17:57
I've now seen this once (out of many times the popup appeared). But no idea how to reproduce.

**Comment by AlanGriffiths** [comment] 2023-11-23 09:58
Fixed by: #3145

**Closed by AlanGriffiths** 2023-11-23 09:58 UTC
Labels: bug
