### ISSUE TITLE
Resizing Mattermost sends it crazy

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2509] opened 2022-07-18 13:23 UTC
1. Open the `mattermost-desktop` snap on a Mir compositor (without hacking it to use Wayland)
2. Try to resize it's window

Expect: window resizes
Actual: window disappears and mattermost hogs a CPU

(This doesn't occur using Wayland, so is likely to do with our Xwayland interaction)

**Comment by mattkae** [comment] 2023-09-21 18:35
Note that this even happens when we fullscreen the mattermost application

**Comment by mattkae** [comment] 2023-09-21 19:03
Fun fact: It does not _disappear_: it just gets a teeny tiny width and height. The _very tiny_ black bar on the left hand side of this image is mattermost:
![Screenshot from 2023-09-21 15-02-36](https://github.com/MirServer/mir/assets/25062299/14774765-5c42-46cf-b1fd-dedb322129db)

**Comment by mattkae** [comment] 2023-09-21 19:41
The problem is that the `WindowInfo::max_width/max_height` are both 1

**Comment by mattkae** [comment] 2023-09-22 15:26
Fixed by #3050

**Closed by mattkae** 2023-09-22 15:26 UTC
