### ISSUE TITLE
Firefox popups take keyboard focus

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#955] opened 2019-08-02 16:35 UTC
In Firefox running native Wayland on Mir, popups take keyboard focus away from the main window. This causes the address bar and fields with username/password autocomplete to be difficult to use.

**Comment by RAOF** [comment] 2019-09-17 14:35
Question: Is Mir mishandling the protocol, or is the protocol not entirely specified.

**Comment by wmww** [comment] 2019-09-17 14:58
"the top most grabbing popup will always have keyboard focus."
\- xdg-shell.xml

```
void mf::XdgPopupStable::grab(struct wl_resource* seat, uint32_t serial)
{
    (void)seat, (void)serial;
    // TODO
}
```
\- xdg_shell_stable.cpp

Clearly we are not paying the `.grab` request as much attention as is needed to correctly move keyboard focus. It appears the FF address bar is not grabbing, and we give all popups the grabbed behavior.

**Comment by RAOF** [comment] 2019-09-17 15:04
Hello! This is #827

**Comment by RAOF** [comment] 2019-09-17 15:05
Duplicate of #827

**Closed** 2020-07-23 14:10 UTC
Labels: bug
